#ifndef CUSTOM_SLICER_HELPERS_H
#define CUSTOM_SLICER_HELPERS_H
#include "surface_solns.h"

// Up to a single column of 50,000 slices
#define MAX_ELEMENTS 1009
#define NUM_BASE_PARAMS 11
#define NUM_PARAMS_PER_SLICE 13

/*
* @brief Basic parameters for validating input.
*/
typedef struct {
    int n_each;
    int n_rows;
    int n_cols;
    int surface_type;
    double dx;
    double dy;
    double gx_width;
    double gx_depth;
    double gy_width;
    double gy_depth;
} GRID_PARAMS_BASIC; // Applies to any grid of surfaces generated by the DLLs, not just image slicers

typedef struct {
    int surface_type;    // 0 = rotationally symmetric conic; 1 = cylindrical conic
    int n_each;          // Number of slices per section
    int n_rows;          // Number of rows of sections
    int n_cols;          // Number of columns of sections
    int angle_mode;      // Pattern generated by gamma

    double dalpha;       // Change in alpha between rows in degrees
    double dbeta;        // Change in beta between columns in degrees
    double dgamma;       // Change in gamma between slices in degrees
    double gamma_offset; // Offset in gamma between rows

    double azps;         // Change in zp between slices
    double dsyx;         // Change in syx between rows
    double dsyz;         // Change in syz between rows
    double dsxy;         // Change in sxy between columns
    double dsxz;         // Change in sxz between columns
    double du;           // Change in u between rows

    double alpha_cen;    // alpha of central row (or avg of 2 central rows if n_rows is even)
    double beta_cen;     // beta of central column (or avg of 2 central columns if n_cols is even)
    double gamma_cen;    // gamma of central slice
    double syx_cen;      // syx of central section
    double syz_cen;      // syz of central section
    double sxy_cen;      // sxy of central section
    double sxz_cen;      // sxz of central section
    double u_cen;        // u of central section

    double dx;           // Slice size along x-axis
    double dy;           // Slice size along y-axis
    double cv;           // Curvature = 1 / R
    double k;            // Conic constant

    double gx_width;     // Width of gaps between columns along x-axis
    double gx_depth;     // Depth (z) of gaps between columns
    double gy_width;     // Width of gaps between slices/rows along y-axis
    double gy_depth;     // Depth (z) of gaps between slices/rows along y-axis
} IMAGE_SLICER_PARAMS_ANGULAR;

typedef struct {
    int surface_type;    // 0 = rotationally symmetric conic; 1 = cylindrical conic
    int n_each;          // Number of slices per section
    int n_rows;          // Number of rows of sections
    int n_cols;          // Number of columns of sections
    int angle_mode;      // Pattern generated by gamma

    double dy0;       // Change in alpha between rows in degrees
    double dx0;        // Change in beta between columns in degrees
    double dd;       // Change in gamma between slices in degrees
    double d_offset; // Offset in gamma between rows

    double azps;         // Change in zp between slices
    double dsyx;         // Change in syx between rows
    double dsyz;         // Change in syz between rows
    double dsxy;         // Change in sxy between columns
    double dsxz;         // Change in sxz between columns
    double du;           // Change in u between rows

    double y0_cen;   
    double x0_cen;   
    double d_cen;   
    double syx_cen;      // syx of central section
    double syz_cen;      // syz of central section
    double sxy_cen;      // sxy of central section
    double sxz_cen;      // sxz of central section
    double u_cen;        // u of central section

    double dx;           // Slice size along x-axis
    double dy;           // Slice size along y-axis
    double cv;           // Curvature = 1 / R
    double k;            // Conic constant
    double f;

    double gx_width;     // Width of gaps between columns along x-axis
    double gx_depth;     // Depth (z) of gaps between columns
    double gy_width;     // Width of gaps between slices/rows along y-axis
    double gy_depth;     // Depth (z) of gaps between slices/rows along y-axis
} IMAGE_SLICER_PARAMS_LINEAR;

void LoadCustomParamsFromFile(double p_custom[], int file_num, char params_dir[]);

SLICE_PARAMS GetSliceParams(int slice_num, int col_num, double p_custom[]);

double GetUForRow(int row_num, double p_custom[]);

int IsAllRowsAligned(double p_custom[]);

GRID_PARAMS_BASIC MakeBasicParamsFromCustom(double p_custom[]);

int ValidateBasicParams(GRID_PARAMS_BASIC* p);

int ValidateSlicerParamsAngular(IMAGE_SLICER_PARAMS_ANGULAR* p);

int ValidateSlicerParamsLinear(IMAGE_SLICER_PARAMS_LINEAR* p);

int IsParametersEqualAngular(IMAGE_SLICER_PARAMS_ANGULAR p1, IMAGE_SLICER_PARAMS_ANGULAR p2);

int IsParametersEqualLinear(IMAGE_SLICER_PARAMS_LINEAR p1, IMAGE_SLICER_PARAMS_LINEAR p2);

void MakeSliceParamsArrayAngular(double p_custom[], IMAGE_SLICER_PARAMS_ANGULAR p);

void MakeSliceParamsArrayLinear(double p_custom[], IMAGE_SLICER_PARAMS_LINEAR p);

double CalcZpFromGamma(double gamma, double cv, double k);

static SLICE_PARAMS GetSliceParamsAngular(int slice_num, int col_num, IMAGE_SLICER_PARAMS_ANGULAR p);

static SLICE_PARAMS GetSliceParamsLinear(int slice_num, int col_num, IMAGE_SLICER_PARAMS_LINEAR p);

#endif